nodeLinker: node-modules

yarnPath: .yarn/releases/yarn-3.4.1.cjs

npmScopes:
  yerkinnn:
    npmRegistryServer: "https://npm.pkg.github.com"
    npmPublishRegistry: "https://npm.pkg.github.com"
    npmAlwaysAuth: true
    # npmAuthToken: "${NODE_AUTH_TOKEN}"
